The idea is a Inc, so the main page is a list with text and stuff, about our company (just put like xxx, so i can 
put the text later), at the top right corner we'll have a Products button, Conact button, an employees button, and a 
EL, button, and also a Shop button.

Every single Product *only not the CPS* has a Add to cart button.

Products -> 
-[Add a NEW tag to this one]
Custumizable Photoshops, or CPS made from out Profesional Editior, Mr.MMMM(make it blue and when clicked links to
the employees page, and it goes directly to MMMM's (an employee)), [also add some PS images i'll give it to you so 
you can implement it]

---   Products --tag-
[Small letter = the tet will appear when hovering the price, for a short time]

1. Glass table. 
$50.13 (small letters->requires assembly)
Img->

2. Watering Can.
$15.10 (small letters->per pound you weigh)
Img->

3. Silverware
$30.23 (small letters->per meal you ever eaten)
Img->

4. Rolling Pin 
$43.76(small letters->per time you have baked something)
Img->

5. Custum Key
$27.97 (small letters->per time you use a key)
Img->

6. Fancy Flippers
$41.99 (small letters->Per time you touch or drink water)
Img->

7. Toiled アトマティックシートウォーマー
$399.99 (small letters->Per time you go to the bathroom)
Img->

8. Touilotu Papu
$12.89 (small letters->per inch of paper you use from the time you buyed this)
Img->

9. Very safe door
$89.99 (small letters->Per time you use a door)


--Contact--
You are able to contact us by either, Being at our HQ at MMS, or by some way shape or form, getting our contat if you
do, we'll have a pleasure on getting your money back or simply talking to ya.


--Employee--


Logan Wall Fencer. (CEO)
Logan, is the CEO and founder of Yates Inc. He has spend a lot of time and effort, making this the greatess company
he could every think of. 

Mr. Michael Mackenzy MCkale Mackelayne. (CPS/HR)
Michael, is who does everything of our desings, and how things will work, he also is our Human Rights manager. Michael also
is one of our 2 first hires, together with Bernardo. Michael is very hard working and is able to acomplish muntiple 
Ps, a day, he one made 60% of our daily ravenue, doing 21 Ps, and 2 30minute long videos do 5M+ subs channels.

Bernardo. (CTO/CFO/LW/SCM)
Bernardo works in three areas, the first thing is he is our Chief Technoly Offficer and makes everything computer related. His 
second area, is Chief Financial Officer and he works with all the money that comes in-n-out. and the last thing, is he's
our comapanyes Lawier, and he’s a Supply Chain Manager. 
He handles partnerships and calls with other companies to get resources or make deals

Dylan Mad Hawk. (PSM)
Dylan is our latest hire, but he is very hard working, he handles everything of managing the resources and putting them
into our products, with the requirements made from the other companies/MMM's desing.

--Shop--

Everytime the Cart button is clicked(the button that adds the items in the shop), a # appear above the Shop cart icon,
when the Shop cart button is clicked a pop-up that cover vertically 1/4ich of the screen at the right absolute right.
You have a unit amount on every product added to the cart, and a delete, button if the product  unint amount is clicked
you can choose to change the amount of the smae item you want (starts at 1 ends at 5).
--

====
Check box, for when you are in the part where you type ur card and shit, before it lets you pay, you need to click Check
in the small lil box, and it says "Please click in the check box, to agree to our Terms of Service"TOS in blue when clickec
goes to the (url)/tos @tos file
=====
If the PAY button is clicked you go to the (url)/shop, then in the shop ->imgs explaning:
@Screenshot 2025-10-23 at 8.12.37 PM.png 
then ->@Screenshot 2025-10-23 at 8.13.29 PM.png 
then ->@Screenshot 2025-10-23 at 8.15.21 PM.png 
then-> @Screenshot 2025-10-23 at 8.16.16 PM.png 


--EL--

*el stands for employee login*

It says:

Log-in:
Employee ID(with that gray text that when is clicked it dissappear)

Password(with that gray text that when is clicked it dissappear):

**Passwords that works for login-> [ID:39187, password:MMMS],
 [ID:123456, password:PSSW], 
 [ID:000001, password:CEOBOSS],
[ID:007411, password:T@llahM2N]
[ID:674121, password:TUFboss]
those are the only combinations that will work, anythings will give an error saying "I'm sorry you typed (id or password)
wrong, please try again, or chekc if you are in the wrong space.
========
Supabase will work like that: Saves:
Name of the Employee, the ID, and Password, and the tasks. The important thing is, all the tasks will appear for everyone
but only the CEO, can delete it, and only the person who was assigned the task can change it's % of being done, also
the CEO can change the due date. But all this Due date, %, ID, Pssw, name, taks, NEED to be in Supabase
========

ID:39187-> is Michael
Id:123456-> Is Bernardo
ID:000001-> IS Logan
ID:007411-> Dylan
ID:674121-> Harris


------> Once logged in as an Employee, you'll get a new section on the home page, the WTBD:
What To Be Done

There it will show all the projects, that the Employees have to work on.
and a % bar of how much % it's done, each task will have a name assigned on it, and a due date. 
Only the person who it is assigned to can change the % how the task from whom it is assigend, also it can only go up,
lever down.
Only the CEO, and Bernarod has the ability to add a task in there, the CEO can diretly acess it in the task page,
and me bernardo can by going in supabse😎(cause im too good).


